### ISSUE TITLE
Support for username in filename

### ISSUE THREAD

**Issue by mdosch** [AluminumTank/wofi-pass#2]
Thank you for this great tool, I think that's exactly what I want as the rofi-pass ydotool branch also has some issues.
But for me there is one thing missing: I have the username as file name and only a password field in the file. So either I have to script something to also write the user name into the files or change all my other pass clients.
I tried to change your tool to also support user names as file names but I didn't succeed. Maybe you know how to add an option for file name based user names?

**Comment by TinfoilSubmarine** [comment]
Hmmmm. So your pass schema is something like this?
```
$ pass
Password Store
├── abc.com
│   └── username
├── another.web.site
     ├── user1
     └── user2
```

I just pushed https://github.com/TinfoilSubmarine/wofi-pass/commit/42699fdbcb7e84c1b9d36783dbfd39afc55e8a1a, give it a shot.

**Comment by mdosch** [comment]
On 19.08.2022 06:37, Joel Beckmeyer wrote:
>Hmmmm. So your pass schema is something like this?
>```
>$ pass
>Password Store
>├── abc.com
>│   └── username
>├── another.web.site
>     ├── user1
>     └── user2
>```

Yes, exactly. Afair that's even the prefered setup of the pass author. 
:)
>
>I just pushed 
>https://github.com/TinfoilSubmarine/wofi-pass/commit/42699fdbcb7e84c1b9d36783dbfd39afc55e8a1a, 
>give it a shot.

Wow, that's exactly what I was looking for.
Thank you very much for adding this feature within a few hours. :)

Best regards,
Martin

**Comment by TinfoilSubmarine** [comment]
Awesome, thanks for confirming.
