### ISSUE TITLE
-s option no longer working

### ISSUE THREAD

**Issue by UltraBlackLinux** [AluminumTank/wofi-pass#4]
Hey there,
It seems like the `-s` option no longer works as expected. It rather always prints the first line even if there are others.
Please fix this!
Thanks!

**Comment by TinfoilSubmarine** [comment]
I cannot reproduce this, could you give me a (obviously fake) example where this happens?

**Comment by UltraBlackLinux** [comment]
> I cannot reproduce this, could you give me a (obviously fake) example where this happens?

After a lot of trying, I could reliably reproduce this with entries consisting of only two lines: One for the password and one for any other:

```
myverysecurepassword
login: thisrandomassaccount
```

**Comment by TinfoilSubmarine** [comment]
What is the exact list of flags/parameters you are passing? When I run `wofi-pass -s` with the example you provided, it still gives me the list of fields.

**Comment by UltraBlackLinux** [comment]
> What is the exact list of flags/parameters you are passing? When I run `wofi-pass -s` with the example you provided, it still gives me the list of fields.

I'm using `wofi-pass -ts`

**Comment by TinfoilSubmarine** [comment]
I think this was related to the defaults not properly being set in all circumstances. Can you check with the latest commit I pushed?

**Comment by UltraBlackLinux** [comment]
> I think this was related to the defaults not properly being set in all circumstances. Can you check with the latest commit I pushed?

Yep, Works! Thank you!

**Comment by UltraBlackLinux** [comment]
could you also update the aur package? The fix has not yet made it there

**Comment by TinfoilSubmarine** [comment]
I don't own that package, kinda suprised there is one but in a good way :) 

Probably need to have some versions tagged to make this work

**Comment by noobping** [comment]
> could you also update the aur package? The fix has not yet made it there

Sure, I updated it immediately.

**Comment by noobping** [comment]
> I don't own that package, kinda suprised there is one but in a good way :)

Do you want ownership?

> Probably need to have some versions tagged to make this work

Github releases would be nice. It is also possible to use the latest commit or tag.

**Comment by TinfoilSubmarine** [comment]
> > I don't own that package, kinda suprised there is one but in a good way :)
> 
> Do you want ownership?

Nah, I'm good. I don't use Arch.
> 
> > Probably need to have some versions tagged to make this work
> 
> Github releases would be nice. It is also possible to use the latest commit or tag.

I'll look into it
