### ISSUE TITLE
Make Search case insensitive

### ISSUE THREAD

**Issue by UltraBlackLinux** [AluminumTank/wofi-pass#5]
Hey there,
I noticed that the search is not case-insensitive, meaning if you type "Test", it will not be able to find "test".
Can you fix this?
Thanks!

**Comment by TinfoilSubmarine** [comment]
This isn't the responsibility of wofi-pass, wofi already provides this.
`$ man 5 wofi`
```
...
insensitive=BOOL
      If true enables case insensitive search, default is false.
...
```

**Comment by UltraBlackLinux** [comment]
Oh I thought it was already insensitive - Interesting
